#!/bin/bash
nm="Floflis' Feofle"
vs="v1"

if [ "$1" = "" ]; then
   feofleversion="""
        \e[1;42m $nm \e[0m\e[100m version $vs \e[0m
        \e[100m Created in 14-05-2021 by Daniella Mesquita \e[0m
"""
   echo "$feofleversion"
   echo "Type 'feofle --help' (without quotes) to see a list of available commands."
   echo "NOTE: Feofle is not ready yet!"
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
   echo "        \e[1;42m $nm $vs \e[0m"
   echo "Use these commands after/together with 'feofle' command."
   echo "Available commands:"
   echo "Information:"
   echo "   --help, -h                  Shows all available commands"
   echo "   --version, -v               Shows the version of $nm"
fi

if [ "$1" = "--version" ] || [ "$1" = "-v" ]; then
   echo "$feofleversion"
fi
