#!/bin/bash
nm="Floflis People"
vs="v1"

if [ "$1" = "" ]; then
   floflispeopleversion="""
        \e[1;42m $nm \e[0m\e[100m version $vs \e[0m
        \e[100m Created in 14-05-2021 by Daniell Mesquita \e[0m
"""
   echo "$floflispeopleversion"
   echo "Type 'people --help' (without quotes) to see a list of available commands."
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
   echo "        \e[1;42m $nm $vs \e[0m"
   echo "Use these commands after/together with 'people' command."
   echo "Available commands:"
   echo "Information:"
   echo "   --help, -h                  Shows all available commands"
   echo "   --version, -v               Shows the version of $nm"
fi

if [ "$1" = "--version" ] || [ "$1" = "-v" ]; then
   echo "$floflispeopleversion"
fi

#- init contacts/people folder
#- wizard add new contact (name/middle/surname, ETH address(es), BTC address(es), ENS name, email(s), address(es), phone(s), IPFS ID, C/Y addresses, chats, social profiles
#- remove a contact
#- implement Web3Updater and list on UniStore

#- command to visualize a contact
#- command to email a contact
#- command to send crypto to a contact
#- command to share crypto address/invoice with a contact
#- command to call a contact
#- command to access site/blog of a contact
#- command to phisically visit a contact (call an app such as Maps and Uber)
#- command to ping a contact (IPFS, C/Y)
#- command to chat with a contact
#- command to visit a social profile of a contact
#- convert CSV > JSON
#- leveraging telephony and other apps, attribute call/notification sound to an specific contact
